# Generated by Django 5.2.15 on 2026-08-18 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Incomplete Application'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified / Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_school', models.CharField(blank=True, max_length=150)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tenth_passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_college', models.CharField(blank=True, max_length=150)),
                ('intermediate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intermediate_passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.CharField(default='B.Tech', max_length=50)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('IT', 'Information Technology')], max_length=10)),
                ('admission_year', models.PositiveIntegerField(default=2026)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academics', to='students.studentprofile')),
            ],
        ),
    ]
