# Generated by Django 5.2.15 on 2026-08-18 17:20

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('10TH_MARKSHEET', '10th Standard Marksheet'), ('12TH_MARKSHEET', '12th Standard Marksheet'), ('GOVT_ID', 'Government ID Proof (Aadhaar/Passport/PAN)'), ('TC', 'Transfer Certificate (TC)'), ('PHOTO', 'Passport Size Photo')], max_length=30)),
                ('file', models.FileField(upload_to=documents.models.student_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
